#app:
#  root_path: ""
#  logs_path: ""

http:
  domain: ""
  debug: false
  host: "0.0.0.0"
  port: 8080
  readTimeout: 10
  writeTimeout: 30
  idleTimeout: 30
  useNginx: true
  useTLS: false
  maxPostSize: 10485760

log:
  level: "info"
  development: false
  disableCaller: true
  disableStacktrace: true
  encoding: "console"
  rotation:
    filename: "app.log"
    maxsize: 5
    maxage: 30
    maxbackups: 100
